### ISSUE TITLE
老哥您好，企业微信API接受消息配置

### ISSUE THREAD

**Issue by wyx2014** [shirayner/weixin-service#1]
企业微信后台配置url保存后一直报 openapi回调地址请求不通过这个错误，我用了你的代码集成到项目中，token和EncodingAESKey都配置了并且把项目启动在公网服务器上，
问题1:我先把项目启动在服务器上，再去企业微信后台配置url，token和EncodingAESKey思路对吗？
还是应该先在企业微信上配置url，token和EncodingAESKey，在去配置代码，为啥url一直保存不了呢？
问题2:会不会是我的服务器设置防火墙，看了企业微信的api，可以取到企业微信发送的ip，这还要动态的配置在我服务器的防火墙上吗？
盼您回复，万分感谢！！！

**Comment by shirayner** [comment]
> 企业微信后台配置url保存后一直报 openapi回调地址请求不通过这个错误，我用了你的代码集成到项目中，token和EncodingAESKey都配置了并且把项目启动在公网服务器上，
> 问题1:我先把项目启动在服务器上，再去企业微信后台配置url，token和EncodingAESKey思路对吗？
> 还是应该先在企业微信上配置url，token和EncodingAESKey，在去配置代码，为啥url一直保存不了呢？
> 问题2:会不会是我的服务器设置防火墙，看了企业微信的api，可以取到企业微信发送的ip，这还要动态的配置在我服务器的防火墙上吗？
> 盼您回复，万分感谢！！！

- 问题一：
> 这个回调地址的配置，你要先去企业微信后台找到那些配置，然后再配置到你配置文件中，具体可参考：https://www.cnblogs.com/shirui/p/7365538.html

- 问题二：
> 我刚试过了，我本地是没有问题的，因此可以排除代码有bug的情况。
> ![callback-sucess](https://user-images.githubusercontent.com/11574340/63396430-9f654d00-c3f9-11e9-9b0e-4510f8706879.jpg)

> 企业微信后台配置的这个回调地址的作用：配置时，企业微信官方服务器那边会朝你配置的这个地址发送请求，所以你看是不是你的服务没法被公网访问的原因。
> 因此初步估计你的问题应该是网络问题了，请检查:
> （1）通过浏览器url访问相关接口,能不能获取对应返回结果。若不能，则说明服务器没法被公网访问，考虑是防火墙或者是不是需要做一个内网穿透
> （2）防火墙有没有开放对应端口

**Comment by wyx2014** [comment]
明白了，我这边先排查网络，您真的是太热心了，
![image](https://user-images.githubusercontent.com/8851315/63405456-7654b480-c419-11e9-942a-3c475367a6d8.png)
那我这边就是http://xxx.com/meeting/weixin/api/msg/callBack,Thanks

**Comment by shirayner** [comment]
> 明白了，我这边先排查网络，您真的是太热心了，
> ![image](https://user-images.githubusercontent.com/8851315/63405456-7654b480-c419-11e9-942a-3c475367a6d8.png)
> 那我这边就是http://xxx.com/meeting/weixin/api/msg/callBack,Thanks

是的，就是这样。哈哈，很高兴能帮到你

**Comment by webott** [comment]
接收消息回调一般是PC版的，可以参考这个 http://www.rotdogmes.cn/#jqrye
功能不少
